replace_like_count_with_nothing:
  default: false
  description:
    en: Turns off the visibility of the like count.

replace_like_count_with_reaction:
  default: false
  description:
    en: Replaces the like count with text saying "Reactions". Note that this setting takes precedence over displaying nothing.

remove_link_clickthrough_click_count:
  default: false
  description:
    en: Turns off the visibility of link clickthrough counts.